/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pudinzinho
 */
import java.util.Scanner;
public class MainFrame extends javax.swing.JFrame {
Conta testando = new Conta();
Scanner input = new Scanner(System.in);
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PushNotification = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        ActionSaque = new javax.swing.JButton();
        ActionDeposito = new javax.swing.JButton();
        ActionExtrato = new javax.swing.JButton();
        ActionExit = new javax.swing.JButton();
        ActionTransacoes = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        SaqueDialog = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        Saque_ValorRecebido = new javax.swing.JTextField();
        BotaoSaque = new javax.swing.JButton();
        ErroValorValido = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NomeContainer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AgenciaContainer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ContaContainer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        PushNotification.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                PushNotificationWindowActivated(evt);
            }
        });

        jLabel5.setText("Dados recebidos com sucesso!");

        jButton2.setText("Ok");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PushNotificationLayout = new javax.swing.GroupLayout(PushNotification.getContentPane());
        PushNotification.getContentPane().setLayout(PushNotificationLayout);
        PushNotificationLayout.setHorizontalGroup(
            PushNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PushNotificationLayout.createSequentialGroup()
                .addGroup(PushNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PushNotificationLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel5))
                    .addGroup(PushNotificationLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jButton2)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        PushNotificationLayout.setVerticalGroup(
            PushNotificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PushNotificationLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jFrame1.setPreferredSize(new java.awt.Dimension(622, 457));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Selecione a operação");

        ActionSaque.setText("Saque");
        ActionSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionSaqueActionPerformed(evt);
            }
        });

        ActionDeposito.setText("Depósito");

        ActionExtrato.setText("Extrato");

        ActionExit.setText("Sair");

        ActionTransacoes.setText("Ultimas Transações");
        ActionTransacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionTransacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(ActionSaque)
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(ActionDeposito)
                        .addGap(18, 18, 18)
                        .addComponent(ActionExtrato)
                        .addGap(18, 18, 18)
                        .addComponent(ActionTransacoes)
                        .addGap(18, 18, 18)
                        .addComponent(ActionExit)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActionSaque)
                    .addComponent(ActionDeposito)
                    .addComponent(ActionExtrato)
                    .addComponent(ActionTransacoes)
                    .addComponent(ActionExit))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jLabel7.setText("Insira o valor a ser retirado");

        Saque_ValorRecebido.setActionCommand("<Not Set>");
        Saque_ValorRecebido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Saque_ValorRecebido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Saque_ValorRecebidoActionPerformed(evt);
            }
        });

        BotaoSaque.setText("Ok");
        BotaoSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSaqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SaqueDialogLayout = new javax.swing.GroupLayout(SaqueDialog.getContentPane());
        SaqueDialog.getContentPane().setLayout(SaqueDialogLayout);
        SaqueDialogLayout.setHorizontalGroup(
            SaqueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaqueDialogLayout.createSequentialGroup()
                .addGroup(SaqueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SaqueDialogLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(BotaoSaque))
                    .addGroup(SaqueDialogLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel7))
                    .addGroup(SaqueDialogLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(Saque_ValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        SaqueDialogLayout.setVerticalGroup(
            SaqueDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaqueDialogLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addComponent(Saque_ValorRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotaoSaque)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Saldo Insuficiente!");

        javax.swing.GroupLayout ErroValorValidoLayout = new javax.swing.GroupLayout(ErroValorValido.getContentPane());
        ErroValorValido.getContentPane().setLayout(ErroValorValidoLayout);
        ErroValorValidoLayout.setHorizontalGroup(
            ErroValorValidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ErroValorValidoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        ErroValorValidoLayout.setVerticalGroup(
            ErroValorValidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ErroValorValidoLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome");

        NomeContainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeContainerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bem vindo ao Generic Bank!");

        jLabel3.setText("Agência(Somente Numero)");

        AgenciaContainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciaContainerActionPerformed(evt);
            }
        });

        jLabel4.setText("Conta");

        ContaContainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContaContainerActionPerformed(evt);
            }
        });

        jButton1.setText("Entrar");
        jButton1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButton1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AgenciaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(ContaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NomeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AgenciaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ContaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PushNotificationWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PushNotificationWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_PushNotificationWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.PushNotification.setVisible(false);
        this.jFrame1.setSize(622,467);
        this.jFrame1.setVisible(true);
          

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.PushNotification.setSize(527, 227);
        this.PushNotification.setLocation(400,400);
        this.PushNotification.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1AncestorAdded

    private void ContaContainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContaContainerActionPerformed

        testando.setNumero(this.ContaContainer.getText());
    }//GEN-LAST:event_ContaContainerActionPerformed

    private void AgenciaContainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgenciaContainerActionPerformed
        testando.setAgencia(this.AgenciaContainer.getText());
    }//GEN-LAST:event_AgenciaContainerActionPerformed

    private void NomeContainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeContainerActionPerformed

        testando.setTitular(this.NomeContainer.getText());
    }//GEN-LAST:event_NomeContainerActionPerformed

    private void ActionSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionSaqueActionPerformed
      this.SaqueDialog.setSize(400,300);
        this.SaqueDialog.setVisible(true);
    }//GEN-LAST:event_ActionSaqueActionPerformed

    private void ActionTransacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionTransacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ActionTransacoesActionPerformed

    private void BotaoSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSaqueActionPerformed
        if(Float.parseFloat(this.Saque_ValorRecebido.getText())<testando.getSaldo()){
           
        }
                
      testando.sacar(Float.parseFloat(this.Saque_ValorRecebido.getText()));
      
    }//GEN-LAST:event_BotaoSaqueActionPerformed

    private void Saque_ValorRecebidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Saque_ValorRecebidoActionPerformed
       
    }//GEN-LAST:event_Saque_ValorRecebidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActionDeposito;
    private javax.swing.JButton ActionExit;
    private javax.swing.JButton ActionExtrato;
    private javax.swing.JButton ActionSaque;
    private javax.swing.JButton ActionTransacoes;
    private javax.swing.JTextField AgenciaContainer;
    private javax.swing.JButton BotaoSaque;
    private javax.swing.JTextField ContaContainer;
    private javax.swing.JDialog ErroValorValido;
    private javax.swing.JTextField NomeContainer;
    private javax.swing.JDialog PushNotification;
    private javax.swing.JDialog SaqueDialog;
    private javax.swing.JTextField Saque_ValorRecebido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
